version: '3'
services:
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    expose:
      - "3000"
    ports:
      - "3000:3000"
  messageproxy:
    depends_on:
      - messageapp
    image: "messageproxy"
    expose:
      - "9001"
    ports:
      - "9001:9001"
    links:
      - "messageapp:messageDB"
  mongodb:
    depends_on:
      - messageapp
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
